### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by fajtak** [dhelmr/ulauncher-tldr#1]
Hi, I really like the idea behind your extension. I installed it but when I try to use it for "ls" or "man" I am getting the endless Loading... item. Do you know what could be the reason?

Thanks in advance

**Comment by dhelmr** [comment]
Hi, I think this means that there was some kind of error and the extension did not start correctly. What OS and python version are you using?

Could you restart ulauncher in a terminal and look if there are any error messages showing up? 

```sh
killall ulauncher && ulauncher -v
```

Are there any files stored in `~/.cache/tldr-python`?

**Comment by fajtak** [comment]
Hi, I restarted the ulauncher and there are no errors at all in the output. I use Ubuntu 20.04.3 and Python 3.8.10. There are plenty of files in the folder:

![tldr](https://user-images.githubusercontent.com/15215407/132354599-64760f37-6745-4a17-ba44-33cca22b337d.png)

When I write only "ma" I get a list of possibilities

![tldr2](https://user-images.githubusercontent.com/15215407/132355048-5b303e3b-7ab7-4f25-b81a-fb4edc71f6a3.png)

however, when the full command is inserted, I see only Loading... : 

![tldr3](https://user-images.githubusercontent.com/15215407/132355232-51c6691c-da72-4cea-8c49-efe998bafb3d.png)

**Comment by dhelmr** [comment]
The error logging was not implemented at this point, sorry for that. I just fixed this and committed to master. 

You should be able to update the extension in Ulauncher's preferences. This won't fix the "Loading..." problem, but at least some error should now be shown.

**Comment by fajtak** [comment]
![tldr4](https://user-images.githubusercontent.com/15215407/132358376-2b25d85b-8cdd-4721-bbe0-156c37fa2e26.png)

**Comment by dhelmr** [comment]
Thank you for the screenshot. The problem was that the referenced `removesuffix`methods are only available with python >= 3.9. Sorry for not checking that before. The code should now be compatible with python 3.8.

 I hope it works now for you.

**Comment by fajtak** [comment]
Now it works like a charm. Thanks a lot. Great extension.

**Comment by dhelmr** [comment]
Glad that you like it. Thanks for reporting!
